# Generated by Django 5.1 on 2024-10-27 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日付'),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='編集日時'),
        ),
    ]
