# Generated by Django 4.2.16 on 2024-11-03 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_created_at_todomodel_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='薬名'),
        ),
    ]
