# Generated by Django 4.2.16 on 2024-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todomodel_duedate_alter_todomodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='todo/picture/', verbose_name='写真'),
        ),
    ]
