# Generated by Django 4.2.16 on 2024-11-21 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todomodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationTodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='予防接種名')),
                ('contents', models.TextField(verbose_name='詳細')),
                ('img', models.ImageField(blank=True, null=True, upload_to='todo/picture/', verbose_name='写真')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日付')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('duedate', models.DateField(default=django.utils.timezone.now, verbose_name='期日')),
            ],
        ),
    ]
