# Generated by Django 4.2.16 on 2024-11-21 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todomodel_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationtodomodel',
            name='duedate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='次回予定日'),
        ),
    ]
